train:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.train}

val:
  _target_: src.datasets.LibrispeechDataset
  part: "dev-clean"
  instance_transforms: ${transforms.instance_transforms.inference}
