_target_:  src.model.DeepSpeechModel
n_feats: 128
conv_params: [
  {
    "in_channels": 1,
    "out_channels": 32,
    "kernel_size": [41, 11],
    "stride": [2, 2]
  },
  {
    "in_channels": 32,
    "out_channels": 32,
    "kernel_size": [21, 11],
    "stride": [2, 1]
  }
]
rnn_params: {
  "num_rnn": 5,
  "rnn_hid": 512,
  "bi": true
}
