defaults:
  - model: deep_speech
  - writer: wandb
  - metrics: beam_search
  - datasets: example_eval
  - dataloader: deep_speech
  - transforms: example_only_instance
  - _self_
inferencer:
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "example" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "model_best.pth" # path to the pretrained model
